# image: https://registry.hub.docker.com/_/rabbitmq
# https://github.com/docker-library/rabbitmq/

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      # EXPOSE 4369 5671 5672 15691 15692 25672
      - '${APP_ER_PORT}:4369'
      - '${APP_MQ_PORT}:5672'
      - '${APP_PORT}:15672'
    environment:
      - RABBITMQ_USER=${APP_USER}
      - RABBITMQ_PASSWORD=${APP_PASSWORD}
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
      - 'rabbitmq_plugins:/plugins'
      - 'rabbitmq_config:/etc/rabbitmq/conf.d'
    command: bash -c "cat /my_cmd > cmd.sh && chmod +x /cmd.sh && /cmd.sh"
    configs:
      - source: my_cmd
      
networks:
  default:
      name: ${APP_NAME}
    
volumes:
  rabbitmq_data:
  rabbitmq_plugins:
  rabbitmq_config:

configs:
  my_cmd:
    file: ./cmd.sh
